### ISSUE TITLE
.csv file Schema

### ISSUE THREAD

**Issue by balzee** [SaahilMadge/Spring-2015-IW#1]
Unable to find the csv file or the schema to generate the csv files

**Comment by SaahilMadge-zz** [comment]
Sorry about that, it should be there now

**Comment by balzee** [comment]
Thank you very much . But ndxtdata.csv is still missing . Could you kindly let me know how to create the file or the schema for it

**Comment by SaahilMadge-zz** [comment]
Just added it, sorry for the delayed response. I don't remember which other files are needed but please let me know if any are missing!
